{"name": "Проверка авторизации курьера при неправильном логине или пароле", "status": "passed", "description": "Авторизуемся под курьером, заполняя поле несуществующим логином/паролем. Получаем сообщение об ошибке \"Учетная запись не найдена\" и код 404", "start": 1718117998885, "stop": 1718117998963, "uuid": "77c1503c-4160-47b8-acea-18462ce401ea", "historyId": "e61275ae0c52d7bf18fd5c1f03117cbc", "testCaseId": "e61275ae0c52d7bf18fd5c1f03117cbc", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_with_invalid_field_login_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "MBAirDmitry.local"}, {"name": "thread", "value": "81946-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}